### ISSUE TITLE
Couldn't that plugin modify the plist on iOS upon install from config.xml variables?

### ISSUE THREAD

**Issue by pke** [ohh2ahh/AppAvailability#34] opened 2016-10-14 22:03 UTC
Modifying build artefacts like anything inside `platform` is always a bad idea. 
Isn't there a way this plugin adds the required protocols to the plist itself based on variables defined in `config.xml` in this plugins config section?

```xml
<plugin name="AppAvailability" spec="lates">
        <param name="protocols" value="1password  ophttp" />
</plugin>    
```

**Comment by ohh2ahh** [comment] 2016-10-15 20:55
@pke Thanks for your feedback. That would certainly improve the build process. Unfortunately I don't have time to look into it, but PR are always welcome. Duplicate of https://github.com/ohh2ahh/AppAvailability/issues/25.

**Closed by ohh2ahh** 2016-10-15 20:55 UTC
